- typegate/deno.lock
- typegate/src/runtimes/typegraph.ts
- typegate/src/web/playground.ts
> Fix introspection

- typegate/src/planner/args.ts
- typegate/tests/type_nodes/ts/union/phone_register.ts
- typegate/tests/type_nodes/union_node_quantifier.py
- typegate/tests/type_nodes/union_node_quantifier_test.ts
This adds handlers for:
* Schema generation for optional fields
* List arguments evaluation
> MET-118: handle optional and list values in t.union

- typegate/src/runtimes/deno/worker.ts
> Fix: Unvalidated dynamic method call

- .pre-commit-config.yaml
- libs/common/src/typegraph.rs
- libs/common/src/typegraph/mod.rs
- libs/common/src/typegraph/types.rs
- libs/common/src/typegraph/validator.rs
- libs/common/src/typegraph/visitor.rs
- meta-cli/src/codegen/deno.rs
- meta-cli/src/typegraph/loader/mod.rs
- meta-cli/src/typegraph/postprocess.rs
- meta-cli/tests/e2e.rs
- meta-cli/tests/e2e/snapshots/e2e__e2e__validator__invalid_injections.snap
- meta-cli/tests/e2e/typegraphs/validator.py
- meta-cli/tests/e2e/validator.rs
- typegate/src/engine.ts
- typegate/src/planner/args.ts
- typegate/src/planner/mod.ts
- typegate/src/runtimes/utils/graphql_inline_vars.ts
- typegate/src/typecheck.ts
- typegate/src/types.ts
- typegate/src/types/typegraph.ts
- typegate/tests/injection/injection.py
- typegate/tests/injection/injection_test.ts
- typegraph/tests/test_dependency.py
- typegraph/typegraph/graph/nodes.py
- typegraph/typegraph/injection.py
- typegraph/typegraph/types.py
- website/static/specs/0.0.1.json
Solve MET-74: Enable injections to be configurable per effect
> feat: Injection switch

- typegate/tests/simple/__snapshots__/class_syntax_test.ts.snap
- typegate/tests/simple/class_syntax_test.ts
- typegraph/python/typegraph/types.py
* Update error message in test
* Allow auto-generated names
> Update class syntax

- typegate/src/system_typegraphs.ts
> fix: enable introspection on system typegraphs

- .pre-commit-config.yaml
- typegate/deno.lock
- typegate/src/services/graphql_service.ts
- typegate/tests/runtimes/http/http.py
- typegraph/core/src/conversion/runtimes.rs
- typegraph/core/src/runtimes/mod.rs
- typegraph/core/wit/typegraph.wit
- typegraph/deno/dev/fix-declarations.sh
- typegraph/deno/src/deps.ts
- typegraph/deno/src/effects.ts
- typegraph/deno/src/imports.ts
- typegraph/deno/src/mod.ts
- typegraph/deno/src/policy.ts
- typegraph/deno/src/runtimes/deno.ts
- typegraph/deno/src/runtimes/graphql.ts
- typegraph/deno/src/runtimes/http.ts
- typegraph/deno/src/runtimes/mod.ts
- typegraph/deno/src/typegraph.ts
- typegraph/deno/src/types.ts
- typegraph/deno/src/utils/type_utils.ts
- typegraph/deno/src/wit.ts
- typegraph/python_next/typegraph_next/__init__.py
- typegraph/python_next/typegraph_next/runtimes/http.py
- whiz.yaml
Solve [MET-215](https://metatype.atlassian.net/browse/MET-215).
> feat(typegraph/sdk): Add Http runtime

- typegate/src/engine/planner/args.ts
- typegate/src/engine/typecheck/input.ts
- typegate/tests/typecheck/__snapshots__/typecheck_test.ts.snap
- typegate/tests/typecheck/typecheck.py
- typegate/tests/typecheck/typecheck_test.ts
Solves MET-268 + fixes an edgecase for "weak validation"
> fix(gate): explicit null on query arg

- dev/lock.yml
- whiz.yaml
Fix lock.yml to set WASM_OPT_VERSION in whiz.yaml
> fix: Fix lock.yml

- typegate/tests/runtimes/prisma/full_prisma_mapping_test.ts
- typegraph/core/src/runtimes/prisma/type_generation/input_type.rs
- typegraph/core/src/runtimes/prisma/type_generation/snapshots/typegraph_core__runtimes__prisma__type_generation__test__create_many Post inp.snap
- typegraph/core/src/runtimes/prisma/type_generation/snapshots/typegraph_core__runtimes__prisma__type_generation__test__create_many Post out.snap
- typegraph/core/src/runtimes/prisma/type_generation/snapshots/typegraph_core__runtimes__prisma__type_generation__test__create_many User inp.snap
- typegraph/core/src/runtimes/prisma/type_generation/snapshots/typegraph_core__runtimes__prisma__type_generation__test__create_many User out.snap
- typegraph/core/src/runtimes/prisma/type_generation/snapshots/typegraph_core__runtimes__prisma__type_generation__test__create_one Post inp.snap
- typegraph/core/src/runtimes/prisma/type_generation/snapshots/typegraph_core__runtimes__prisma__type_generation__test__create_one User inp.snap
- typegraph/core/src/runtimes/prisma/type_generation/snapshots/typegraph_core__runtimes__prisma__type_generation__test__update_many Post inp.snap
- typegraph/core/src/runtimes/prisma/type_generation/snapshots/typegraph_core__runtimes__prisma__type_generation__test__update_many User inp.snap
- typegraph/core/src/runtimes/prisma/type_generation/snapshots/typegraph_core__runtimes__prisma__type_generation__test__update_one Post inp.snap
- typegraph/core/src/runtimes/prisma/type_generation/snapshots/typegraph_core__runtimes__prisma__type_generation__test__update_one User inp.snap
- Add missing `create: [ ... ]` and `connect: [ ... ]`
Solves [MET-304](https://metatype.atlassian.net/jira/software/c/projects/MET/boards/2?selectedIssue=MET-304)
> feat(prisma):  connect/create many relation

- dev-tools/.vscodeignore
- dev-tools/README.md
- dev-tools/logo.png
- dev-tools/package.json
- Added a better display name and description
- Added logo and README
> feat(vscode-ext): Logo, README, display name, description

- typegraph/node/sdk/src/policy.ts
- typegraph/node/sdk/src/typegraph.ts
- typegraph/node/sdk/src/types.ts
- typegraph/node/sdk/tsconfig.json
- whiz.yaml
Easier translation from python to typescript typegraph.
N/A
> feat(node): node fontend missing features

- .ghjk/lock.json
- website/docs/tutorials/quick-start/index.mdx
Documentation is missing.
_No changes needed._
> docs: Getting started guide for the vscode extension

- examples/demo/metatype.yml
- examples/deploy/deploy.mjs
- examples/deploy/deploy.py
- examples/metatype.yaml
- examples/templates/deno/metatype.yaml
- examples/templates/node/metatype.yaml
- examples/templates/python/metatype.yaml
- examples/typegraphs/authentication.py
- examples/typegraphs/authentication.ts
- typegate/src/sync/replicated_map.ts
- typegate/tests/e2e/cli/deploy_test.ts
- typegate/tests/metagen/metagen_test.ts
- website/docs/guides/securing-requests/index.mdx
- website/docs/reference/meta-cli/configuration-file.mdx
- website/docs/reference/runtimes/prisma/index.mdx
- website/docs/reference/typegate/authentication/index.mdx
- website/docs/tutorials/metatype-basics/index.mdx
- website/shared/s3/index.mdx
Fix secret passing in examples and documentation.
Followup to #666.
_N/A_
> fix: fix secret passing

- examples/metatype.yaml
- examples/typegraphs/authentication.py
- examples/typegraphs/authentication.ts
- examples/typegraphs/cors.py
- examples/typegraphs/cors.ts
- examples/typegraphs/example_rest.py
- examples/typegraphs/example_rest.ts
- examples/typegraphs/policies.py
- examples/typegraphs/policies.ts
- examples/typegraphs/scripts/createVote.ts
- website/docs/guides/external-functions/index.mdx
- website/docs/guides/securing-requests/authentication.graphql
- website/docs/guides/securing-requests/index.mdx
- website/docs/guides/securing-requests/policies.graphql
- website/shared/cors/index.mdx
- website/shared/s3/index.mdx
Improves `/gudes/securing-requests/`
_N/A_
_N/A_
> docs: improve `/guides/securing-requests/`

- examples/metatype.yaml
- examples/typegraphs/authentication.py
- examples/typegraphs/authentication.ts
- examples/typegraphs/cors.py
- examples/typegraphs/cors.ts
- examples/typegraphs/example_rest.py
- examples/typegraphs/example_rest.ts
- examples/typegraphs/files-upload.py
- examples/typegraphs/files-upload.ts
- examples/typegraphs/policies.py
- examples/typegraphs/policies.ts
- examples/typegraphs/scripts/createVote.ts
- website/docs/guides/external-functions/index.mdx
- website/docs/guides/files-upload/index.mdx
- website/docs/guides/rest/index.mdx
- website/docs/guides/securing-requests/authentication.graphql
- website/docs/guides/securing-requests/index.mdx
- website/docs/guides/securing-requests/policies.graphql
- website/docs/reference/ecosystem/index.mdx
- website/shared/cors/index.mdx
- website/shared/s3/index.mdx
- Improvements to `/guides/rest`
- Improvements to `/reference/ecosystem`
_N/A_
_N/A_
> docs: improves `/guides/rest`

- website/docs/reference/programmatic-deployment/index.mdx
Add missing docs for `tgDeploy`, `tgRemove`
None
> docs: add `reference/programmatic-deployment/`

- .github/workflows/tests.yml
Fix the NPM registry config in the Github tests.
_N/A_
> fix(gh-tests): Fix local npm registry config

- .ghjk/lock.json
- website/docs/concepts/architecture/index.mdx
- website/docs/concepts/comparisons/index.mdx
- website/shared/install/meta-cli.mdx
- website/shared/projects/first-project.mdx
- Adds a comparison table between metatype and other similar services.
- Add artifact upload protocol to `Architecture` section in docs.
[MET-443](https://linear.app/metatypedev/issue/MET-443/include-comparisons-with-other-products-similar-to-metatype)
_No Migration Needed_
> docs: add a comparison b/n metatype and other similar solutions/products.

- .github/workflows/release.yml
- .pre-commit-config.yaml
- poetry.lock
- typegraph/python/poetry.lock
- Fixes poetry lockfile and adds pre-commit hook to prevent issue from happening
> fix(ci): poetry lockfile

- .ghjk/lock.json
- website/docs/guides/programmatic-deployment/index.mdx
- website/shared/projects/tab-first-project-python.mdx
- website/shared/projects/tab-first-project-ts.mdx
[MET-587](https://linear.app/metatypedev/issue/MET-587/docs-fix-programmatic-deployment-guides)
-
_No Migration Needed_
...
> fix(docs): Fix programmatic deployment guides

- .github/workflows/release.yml
- dev/Dockerfile
- dev/cross.Dockerfile
- dev/tasks-install.ts
Fix issue with the three remaining failing jobs.
...
> fix: broken release pipeline 2

- .github/workflows/release.yml
- dev/cross.Dockerfile
- dev/tasks-build.ts
- Remove accidental dry-run from jsr publish
- Fix cross dockerfile
...
> fix: release pipeline 3

- .ghjk/lock.json
- website/package.json
- website/packages/code-loader-transform.js
- website/pnpm-lock.yaml
- website/src/theme/Root.js
- Gleap.io was removed a while back
- this adds it back so visitors can open ticket and suggest feedback
- internally, we will use this to fine tune the documentation
> feat: add back gleap

- Cargo.lock
- Cargo.toml
- dev/consts.ts
- examples/templates/deno/api/example.ts
- examples/templates/deno/compose.yml
- examples/templates/node/compose.yml
- examples/templates/node/package.json
- examples/templates/python/compose.yml
- examples/templates/python/pyproject.toml
- libs/common/Cargo.toml
- libs/metagen/tests/mat_rust/Cargo.toml
- libs/pyrt_wit_wire/pyproject.toml
- libs/xtask/Cargo.toml
- meta-cli/Cargo.toml
- meta-lsp/package.json
- meta-lsp/ts-language-server/package.json
- meta-lsp/vscode-metatype-support/package.json
- pyproject.toml
- typegate/src/runtimes/wit_wire/mod.ts
- typegate/tests/metagen/__snapshots__/metagen_test.ts.snap
- typegate/tests/runtimes/wasm_reflected/rust/Cargo.toml
- typegraph/core/Cargo.toml
- typegraph/core/src/global_store.rs
- typegraph/deno/sdk/jsr.json
- typegraph/python/pyproject.toml
- typegraph/python/typegraph/__init__.py
> chore: bump to 0.4.7-0

- .github/workflows/release.yml
- Cargo.lock
- Cargo.toml
- dev/consts.ts
- examples/templates/deno/api/example.ts
- examples/templates/deno/compose.yml
- examples/templates/node/compose.yml
- examples/templates/node/package.json
- examples/templates/python/compose.yml
- examples/templates/python/pyproject.toml
- libs/common/Cargo.toml
- libs/metagen/tests/mat_rust/Cargo.toml
- libs/pyrt_wit_wire/pyproject.toml
- libs/xtask/Cargo.toml
- meta-cli/Cargo.toml
- meta-lsp/package.json
- meta-lsp/ts-language-server/package.json
- meta-lsp/vscode-metatype-support/package.json
- pyproject.toml
- typegate/src/runtimes/wit_wire/mod.ts
- typegate/tests/metagen/__snapshots__/metagen_test.ts.snap
- typegate/tests/runtimes/wasm_reflected/rust/Cargo.toml
- typegraph/core/Cargo.toml
- typegraph/core/src/global_store.rs
- typegraph/deno/sdk/jsr.json
- typegraph/python/pyproject.toml
- typegraph/python/typegraph/__init__.py
- Bump prerelease
- Fix minor issue with release pipeline
> chore: bump to 0.4.8-0

- website/docs/reference/runtimes/kv/index.mdx
I discover an issue in the KV runtime documentation 
[kvruntime docs](https://metatype.dev/docs/reference/runtimes/kv)
> fix: table method for kv runtime

- .github/workflows/release.yml
- Cargo.lock
- Cargo.toml
- examples/templates/deno/compose.yml
- examples/templates/node/compose.yml
- examples/templates/node/package.json
- examples/templates/python/compose.yml
- examples/templates/python/pyproject.toml
- pyproject.toml
- src/meta-lsp/LICENSE.md
- src/meta-lsp/logo.png
- src/meta-lsp/package.json
- src/meta-lsp/ts-language-server/package.json
- src/meta-lsp/vscode-metatype-support/package.json
- src/pyrt_wit_wire/pyproject.toml
- src/typegate/src/runtimes/wit_wire/mod.ts
- src/typegraph/core/Cargo.toml
- src/typegraph/core/src/global_store.rs
- src/typegraph/deno/deno.json
- src/typegraph/python/pyproject.toml
- src/typegraph/python/typegraph/__init__.py
- src/xtask/Cargo.toml
- tests/metagen/__snapshots__/metagen_test.ts.snap
- tests/runtimes/wasm_reflected/rust/Cargo.toml
- tools/Cross.toml
- tools/consts.ts
- Fix the minor issues with rc1
- Bump to rc2
> chore(release): prepare 0.4.9-rc2

- Cargo.lock
- Cargo.toml
- examples/templates/deno/compose.yml
- examples/templates/node/compose.yml
- examples/templates/node/package.json
- examples/templates/python/compose.yml
- examples/templates/python/pyproject.toml
- pyproject.toml
- src/meta-lsp/package.json
- src/meta-lsp/ts-language-server/package.json
- src/meta-lsp/vscode-metatype-support/package.json
- src/pyrt_wit_wire/pyproject.toml
- src/typegate/src/runtimes/wit_wire/mod.ts
- src/typegraph/core/Cargo.toml
- src/typegraph/core/src/global_store.rs
- src/typegraph/deno/deno.json
- src/typegraph/python/pyproject.toml
- src/typegraph/python/typegraph/__init__.py
- src/xtask/Cargo.toml
- tests/metagen/__snapshots__/metagen_test.ts.snap
- tests/runtimes/wasm_reflected/rust/Cargo.toml
- tools/Cross.toml
- tools/consts.ts
- tools/cross.Dockerfile
- Bump version to v0.4.9
- Fix issue with cross config context
> chore: bump to v0.4.9

- .github/workflows/release.yml
- Cargo.lock
- Cargo.toml
- LICENSE.md
- deno.lock
- examples/deno.lock
- examples/templates/deno/api/example.ts
- examples/templates/deno/compose.yml
- examples/templates/node/compose.yml
- examples/templates/node/package.json
- examples/templates/python/compose.yml
- examples/templates/python/pyproject.toml
- ghjk.ts
- pyproject.toml
- src/meta-cli/Cargo.toml
- src/meta-lsp/package.json
- src/meta-lsp/ts-language-server/package.json
- src/meta-lsp/vscode-metatype-support/package.json
- src/pyrt_wit_wire/pyproject.toml
- src/typegate/src/runtimes/wit_wire/mod.ts
- src/typegraph/core/Cargo.toml
- src/typegraph/core/src/global_store.rs
- src/typegraph/deno/deno.json
- src/typegraph/python/pyproject.toml
- src/typegraph/python/typegraph/__init__.py
- src/xtask/Cargo.toml
- tests/e2e/templates/templates_test.ts
- tests/metagen/__snapshots__/metagen_test.ts.snap
- tests/runtimes/wasm_reflected/rust/Cargo.toml
- tools/consts.ts
> chore: bump to v0.4.10

- docs/metatype.dev/docs/reference/runtimes/grpc/grpc.graphql
- docs/metatype.dev/docs/reference/runtimes/grpc/index.mdx
> fix(docs): grpc docs

- installer.sh
- Remplacement PR for #843.
- ...
...
> fix(cli): change default installation directory

- src/meta-cli/src/secrets.rs
- src/typegraph/core/src/utils/oauth2/std.rs
- Fix secret hydration
- Fix Google OAuth2 profile type
_N/A_
---
> fix: Fix secret hydration
