metatypedev/metatype

Cargo.lock
meta-cli/Cargo.toml

Link `openssl` statically to avoid the need of installing `libssl` for `meta-cli`.
Before these changes:
```
// ldd meta
- linux-vdso.so
- libbz2.so
- libssl.so
- libcrypto.so
- libgcc_s.so
- libm.so
- libc.so
- /lib/ld-linux.so
```
After these changes:
```
// ldd meta
- linux-vdso.so
- libbz2.so
- libgcc_s.so
- libm.so
- libc.so
- /lib/ld-linux.so
```

feat(meta-cli): link `openssl` statically

---

Cargo.lock
Cargo.toml
typegate/native/src/runtimes/prisma/engine_import.rs

Outdated Cargo.lock is causing problems when installing meta-cli from source code.

chore: update Cargo.lock

---

meta-cli/src/cli/codegen.rs

This allows to run `meta codegen deno --file <FILE>` without the need of a config file.

chore(meta-cli/codegen): make config file optional

---

typegraph/python/typegraph/graph/typegraph.py
typegraph/python/typegraph/types.py

This fixes a few typing issues required to make the sure the `example.py` file we get when following the tutorial doesn't raise any error with Pyright.

fix: Python typing error happening in `example.py` file

---

Cargo.lock
libs/deno/src/lib.rs
libs/xtask/src/deno.rs

Adds support for end of flags arguments to the `cargo x deno test/bench` commands.
Fix an issue that preventing a updating snapshots as implemented in the `dev/test.ts` script.

fix(xtask): add support for end of flags and typechecking

---

.github/pull_request_template.md
.github/workflows/release.yml
.github/workflows/tests.yml
cliff.toml

Configures the `checkout` action step in the workflow that generates the workflow to clone the full git history.
The updates to the release workflow that introduce [git cliff](https://git-cliff.org/) based changelogs (back in #487) don't appear to be in effect.
No end user changes required.

fix(ci): release changelog generation

---

.github/workflows/release.yml

`jco` output path is wrong.
N/A

fix(ci): bug in `typegraph` release job

---

.ghjk/lock.json
.github/workflows/release.yml
.github/workflows/tests.yml

- Manual trigger for release wflow
- Adds missing ghjk step for `vscode-extension` release job
Provides recovery path for when things break.
Doesn't affect end users.

refactor(ci): `workflow_dispatch` for release wflow

---

.github/workflows/release.yml

Fix small typo. Surprised `act` didn't catch this, it must evaluate expressions lazily.

fix(ci): typo in release.yml

---

.github/workflows/release.yml

What it says on the tin can. Also fixes a typo in the `vscode-extension` job.
Manual re-release breaks otherwise as seen [here](https://github.com/metatypedev/metatype/actions/runs/7508564194/job/20444227861).

fix(ci): force/skip push to registries on manual release

---

.github/workflows/release.yml

Oof, I can't believe I missed these. The publish steps are hard to test locally with `act` so ig they require extra scrutiny.
Bug on manual dispatch of `releasae` wflow.

fix(ci): typos in release.yml

---

.github/workflows/release.yml

Another minor issue with the release workflow.
Failure in release run [here](https://github.com/metatypedev/metatype/actions/runs/7521755432/job/20472963653).

fix(ci): mismatch in location of `$AZURE_DEVOPS_TOKEN`

---

dev/deps.ts
dev/test.ts
libs/common/src/typegraph/runtimes/prisma.rs
typegate/src/runtimes/prisma/hooks/generate_schema.ts
typegate/src/typegraph/types.ts
typegate/tests/runtimes/prisma/full_prisma_mapping.py
typegate/tests/runtimes/prisma/full_prisma_mapping_test.ts
typegate/tests/runtimes/prisma/schema_generation.py
typegate/tests/runtimes/prisma/schema_generation_test.ts
typegraph/core/src/runtimes/prisma/constraints.rs
typegraph/core/src/runtimes/prisma/context.rs
typegraph/core/src/runtimes/prisma/id_fields.rs
typegraph/core/src/runtimes/prisma/mod.rs
typegraph/core/src/runtimes/prisma/model.rs
typegraph/core/src/runtimes/prisma/type_generation/query_unique_where_expr.rs
website/static/specs/0.0.3.json

Adds support for more advanced id fields and unique constraints:
- Multi-field id
- Id on struct (foreign key)
- Multi-field unique constraints
- Unique constraint on struct (foreign key)
Support these kind of construct:
```python
user = t.struct(
{
"authProvider": t.string().from_context("provider"),
"profileId": t.string().from_context("profile.id"),
},
config={"id": ["authProvider", "profileId"]},
).rename("User")
project = t.struct(
{
"id": t.uuid(as_id=True, config=["auto"]),
"owner": g.ref("Account"),
"name": t.string(min=3, pattern="^[A-Za-z_-]$"),
},
config={"unique": [["owner", "name"]]}
).rename("Project")
```
_No migration needed._

feat(prisma): Add support multi-field ids and id on struct

---

typegate/src/services/auth/mod.ts
typegate/src/services/auth/protocols/oauth2.ts
typegate/tests/auth/auth_test.ts
typegraph/python/typegraph/graph/params.py

Flatten profile fields in the context.
So instead of
```js
{
provider: 'github',
accessToken: 'xxxxxxxxxxxxxxxxxxxxxxxxxx',
refreshToken: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
refreshAt: 1704717676,
profile: { id: '43663718' },
exp: 1707280877,
iat: 1704688876
}
```
we would have:
```js
{
provider: 'github',
accessToken: 'xxxxxxxxxxxxxxxxxxxxxxxxxx',
refreshToken: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
refreshAt: 1704717676,
'profile.id': '43663718',
exp: 1707280877,
iat: 1704688876
}
```
It was impossible to get the nested id into a `from_context` injection.
Now we can inject `.from_context("profile.id")`.

feat: flattened context

---

typegate/engine/src/lib.rs
typegate/src/main.ts
typegate/src/runtimes/deno/deno.ts
typegate/src/runtimes/deno/worker.ts

When using the dynamic `import` function, if you provide it a raw path like `/foo/bar/baz` and deno detects the current module's loaded from a remote host, it'll convert it to a http url. Reasonable behavior but it turned out to be the cause of #560.
This pr fixes this issue along with:
- Puts contents of `main.ts` in a try/catch block for better error logging.
- Fixes minor permission bugs with the bundled runtime.
#560 
_No changes required_

fix(cli, typegate): explicitly import DenoRuntime.import modules from path

---

.github/workflows/release.yml

Small typo blocking the job that pushes the images to ghcr.io.
[Broken run.](https://github.com/metatypedev/metatype/actions/runs/7748712325/job/21132659221)
_No changes required._

fix(ci): minor typo in `release.yml/docker`

---

.github/workflows/release.yml

Yes, another one lol. This removes the `target` param from the release builder which will default to the last stage of the Dockerfile, the `epoint` stage.  I elected to remove the parameter rather than replacing the value in order to remove one more place future changes will have to consider. (convention better than configuration the saying goes (i think)).
The `typegate` images currently have the wrong target and thus the wrong `entrypoint` command.
_No changes required_

fix: hotfix typo in `release.yml`

---

typegate/tests/regression/invalid_ref_error_message/invalid_ref.py
typegate/tests/regression/invalid_ref_error_message/invalid_ref_test.ts
typegraph/python/typegraph/graph/typegraph.py

Check and throw the error for the `expose` function when called from the Python SDK.
We got a finalization failure when there are some unregistered type referenced with `g.ref`.
_No changes needed._

fix: Show error message for unregistered type name

---

.github/workflows/release.yml
Cargo.lock
dev/lock.yml
installer.sh
website/shared/install/meta-cli.mdx

Switch the default `meta-cli` release to the fat version (the one that includes the `typegate` subcommand).
Tackles #MET-400
The fat cli requires `libwasmedge.so` to be present. Users will need to install or switch to the `meta-cli-thin` release.

refactor!: make fat `meta-cli` the default

---

typegate/src/engine/planner/parameter_transformer.ts
typegate/src/engine/typecheck/input.ts
typegate/tests/params/apply.py
typegate/tests/params/apply_test.ts
typegate/tests/typecheck/__snapshots__/input_validator_test.ts.snap
typegate/tests/typecheck/input_validator_test.ts

Fix type validators for apply from context.
Bug.
_N/A_

fix: apply from context

---

typegate/src/runtimes/random.ts
typegate/tests/random/injection/random_injection.py
typegate/tests/random/injection/random_injection_test.ts
typegate/tests/random/random.ts
typegate/tests/random/random_test.ts
typegate/tests/runtimes/prisma/mixed_runtime_test.ts
typegate/tests/typecheck/type_alias_test.ts

add either, enum, struct and union type support in Random Runtime. 
generating random values for enums, either and union types was failing. 
_No Migrations Needed

fix(gate): `RandomRuntime` does not consider `enum`, `either`, `union` variants

---

typegate/tests/e2e/cli/deploy_test.ts
typegate/tests/e2e/cli/dev_test.ts
typegate/tests/e2e/cli/undeploy_test.ts
typegate/tests/e2e/nextjs/apollo_test.ts
typegate/tests/e2e/self_deploy/self_deploy_test.ts
typegate/tests/e2e/templates/templates_test.ts
typegate/tests/internal/internal_test.ts
typegate/tests/introspection/introspection_test.ts
typegate/tests/introspection/union_either_test.ts
typegate/tests/prisma_migrate/prisma_migrate_test.ts
typegate/tests/runtimes/deno/deno_test.ts
typegate/tests/runtimes/python_wasi/python_wasi_test.ts
typegate/tests/runtimes/temporal/temporal_test.ts
typegate/tests/runtimes/typegate/typegate_prisma_test.ts
typegate/tests/runtimes/typegate/typegate_runtime_test.ts
typegate/tests/runtimes/wasmedge/wasmedge_test.ts
typegate/tests/simple/class_syntax_test.ts
typegate/tests/type_nodes/array_of_optional_test.ts
typegate/tests/type_nodes/either_test.ts
typegate/tests/type_nodes/union_node_attr_test.ts
typegate/tests/type_nodes/union_node_quantifier_test.ts
typegate/tests/type_nodes/union_test.ts
typegate/tests/utils/autotest.ts
typegate/tests/utils/test.ts
whiz.yaml

Pass the test options in the first parameter along with the test name/description.
Avoid scrolling to the end of the test function to see/update the test options.
_N/A_

refactor: pass test options in the first parameter

---

.github/workflows/publish-website.yml
.github/workflows/release.yml
.github/workflows/tests.yml
Cargo.lock
dev/lock.yml
meta-cli/src/typegraph/loader/mod.rs
typegate/deno.jsonc

- Bumps `setup-ghjk` action version to latest unstable.
- Fixes the default node sdk loader command to prevent hang when `tsx` is not installed.
- Publish website pipeline was broken due to ghjk version mismatch.
_N/A_

fix(ci): bump `setup-ghjk` version

---

meta-cli/src/main.rs

Remove log level override by the verbosity flag when no flag is present.
It will default to the configured env_logger default level (or env variable).
...
The default log level became "error" after #664, and `RUST_LOG` environment variable where ignored.
_N/A_

fix: Do not override log level when no verbosity flag is present

---

Cargo.lock
typegate/engine/Cargo.toml
typegate/engine/src/runtimes/wasm/conversion.rs
typegraph/core/Cargo.toml
typegraph/core/src/lib.rs
typegraph/core/wit/typegraph.wit

Motivations:
* Major API changes in wasmtime that affected the type conversion
https://github.com/bytecodealliance/wasmtime/pull/8062
* Major API changes in wit-bindgen (required semicolon in wit, introduction of macro `export!(...)`)
https://github.com/bytecodealliance/wit-bindgen/releases/tag/wit-bindgen-cli-0.14.0
https://github.com/bytecodealliance/wit-bindgen/releases/tag/v0.24.0
None

chore(sdk,gate): bump wasmtime to 20.0.0 and wit-bindgen to 0.24.0

---

ghjk.ts
libs/pyrt_wit_wire/main.py
typegate/engine/runtime.d.ts
typegate/engine/src/runtimes/wit_wire.rs
typegate/src/engine/query_engine.ts
typegate/src/runtimes/Runtime.ts
typegate/src/runtimes/python.ts
typegate/src/runtimes/wit_wire/mod.ts
typegate/src/services/auth/protocols/oauth2.ts
typegate/src/services/graphql_service.ts
typegate/tests/runtimes/python/py/hello.py
typegate/tests/runtimes/python/python.py
typegate/tests/runtimes/python/python.ts
typegate/tests/runtimes/python/python_test.ts

Implements python runtime support for `import_function` materializers. This is an stacked PR on #673 which itself is appended on #687 for tackling MET-404.
This PR introduced a breaking change in the importer logic for python modules brought in through `pyrt.import_` and it's deps. After this PR, any path imports must be prefixed with `.`, `..`, `...` and so to point to relative path locations. This behavior is at odds with standard python which looks for relative modules and packages even if there are no dot prefixes.

feat(pyrt)!: `import_function` materializer support

---

examples/metatype.yaml
meta-cli/src/deploy/actors/task.rs
meta-cli/src/deploy/actors/task_manager.rs
typegraph/node/sdk/src/io.ts
typegraph/node/sdk/src/tg_deploy.ts
typegraph/node/sdk/src/tg_manage.ts
whiz.yaml

- Fix casing typo in the typescript sdk
- Fix error reporting in the typescript sdk
- Display the retry number
- Warning on cancelled retry
N/A

fix: failed typegraph deployment

---

.ghjk/lock.json
.github/workflows/tests.yml
.pre-commit-config.yaml
ghjk.ts
typegate/tests/runtimes/temporal/temporal_test.ts

- Bump the temporal cli used by the tests to 0.13.1
Motivated by the flakey temporal issue. [This](https://github.com/metatypedev/metatype/actions/runs/9264921959/job/25488342071#step:10:16890) line seems to be the key issue which leads me to [this](https://github.com/temporalio/temporal/issues/5123) ticket upstream. It was fixed back in November it seems and moving to the latest version of the temporal server should help solve the issue.
This PR is a stacked diff on top of #754

chore: bump temporal_cli to 0.13.1

---

CONTRIBUTING.md
Cargo.lock
examples/typegraphs/microservice-orchestration.py
examples/typegraphs/microservice-orchestration.ts
website/packages/code-loader-transform.js

- fix the typegraphs that were incorrectly formatted

fix: missing typegraphs

---

.ghjk/lock.json
typegate/tests/docs/how-tos/prog_deploy/prog_deploy.py
typegate/tests/docs/how-tos/prog_deploy/prog_deploy.ts
typegate/tests/docs/how-tos/prog_deploy/prog_deploy_test.ts
typegate/tests/docs/how-tos/prog_deploy/prog_remove.py
typegate/tests/docs/how-tos/prog_deploy/prog_remove.ts
typegate/tests/docs/how-tos/prog_deploy/scripts/say_hello.ts
typegate/tests/e2e/self_deploy/self_deploy_test.ts
typegate/tests/utils/test.ts
typegraph/node/sdk/src/tg_deploy.ts
typegraph/python/typegraph/graph/tg_deploy.py
website/blog/2024-05-09-programmatic-deployment/index.mdx
website/docs/guides/programmatic-deployment/index.mdx

[MET-591](https://linear.app/metatypedev/issue/MET-591/docstest-test-example-script-for-tg-deploy)
-
_No Migrations Needed_
...

chore: add programmatic deploy tests

---

Cargo.lock
Cargo.toml
dev/consts.ts
dev/tasks-lock.ts
examples/templates/deno/api/example.ts
examples/templates/deno/compose.yml
examples/templates/node/compose.yml
examples/templates/node/package.json
examples/templates/python/compose.yml
examples/templates/python/pyproject.toml
libs/common/Cargo.toml
libs/metagen/tests/mat_rust/Cargo.toml
libs/pyrt_wit_wire/pyproject.toml
libs/xtask/Cargo.toml
meta-cli/Cargo.toml
meta-lsp/package.json
meta-lsp/ts-language-server/package.json
meta-lsp/vscode-metatype-support/package.json
pyproject.toml
typegate/src/runtimes/wit_wire/mod.ts
typegate/tests/e2e/upgrade/upgrade_test.ts
typegate/tests/metagen/__snapshots__/metagen_test.ts.snap
typegate/tests/runtimes/wasm_reflected/rust/Cargo.toml
typegraph/core/Cargo.toml
typegraph/core/src/global_store.rs
typegraph/python/pyproject.toml
typegraph/python/typegraph/__init__.py

Prepare release of the 0.4.4 version.

chore: bump to version 0.4.4

---

meta-cli/src/cli/deploy.rs
meta-cli/src/cli/dev.rs

- Make the backoff configurable through the `--retry` and `--retry-interval-ms` options.
- The default max retry count is changed to 0 on the default mode, and remains 3 on the watch mode.
- The `--max-parallel-loads` option has been renamed to `--threads`.
The `--max-parallel-loads` option has been renamed to `--threads`.

feat(cli)!: configurable backoff

---

.ghjk/lock.json
typegate/tests/runtimes/s3/s3_test.ts
typegraph/deno/sdk/jsr.json
typegraph/deno/sdk/src/deps/mod.ts
typegraph/deno/sdk/src/envs/cli.ts
typegraph/deno/sdk/src/metagen.ts
typegraph/deno/sdk/src/policy.ts
typegraph/deno/sdk/src/providers/aws.ts
typegraph/deno/sdk/src/providers/prisma.ts
typegraph/deno/sdk/src/providers/temporal.ts
typegraph/deno/sdk/src/runtimes/deno.ts
typegraph/deno/sdk/src/runtimes/python.ts
typegraph/deno/sdk/src/runtimes/random.ts
typegraph/deno/sdk/src/runtimes/wasm.ts
typegraph/deno/sdk/src/typegraph.ts
typegraph/deno/sdk/src/types.ts
typegraph/deno/sdk/src/utils/func_utils.ts

- Add symbol documentations
- Fix slow types
-
...

refactor: improve JSR score (part 1)

---

.ghjk/lock.json
Cargo.lock
src/substantial/Cargo.toml
src/substantial/proto-gen.sh
src/substantial/protocol/events.proto
src/substantial/src/converters.rs
src/substantial/src/protocol/events.rs
src/typegate/engine/runtime.d.ts
src/typegate/src/runtimes/substantial/agent.ts
src/typegate/src/runtimes/substantial/deno_context.ts
src/typegate/src/runtimes/substantial/types.ts
src/typegate/src/runtimes/substantial/worker.ts
tests/runtimes/substantial/common.ts
tests/runtimes/substantial/imports/common_types.ts
tests/runtimes/substantial/kv_like_test.ts
tests/runtimes/substantial/redis_test.ts
tests/runtimes/substantial/substantial.py
tests/runtimes/substantial/workflow.ts
tools/tasks/install.ts

Port and improve retry/timeout.
N/A

feat(subs): retry + timeout on save

---

src/substantial/src/backends/redis.rs
src/typegate/src/runtimes/substantial/agent.ts
src/typegate/src/runtimes/substantial/workflow_worker_manager.ts

Follow up of #863
When multiple start occurs for redis, some schedules can happen **exactly** at the same time resulting into the same identifier (and leading to an inconsistent state).
This solution simply combines the `schedule` with the run_id making it unique instead of using it as is.
```gql
mutation AllAtOnce {
a: start_retry(kwargs: { .. }) # => calls add_schedule( ... date ...)
b: start_retry(kwargs: { .. })
c: start_retry(kwargs: { .. })
d: start_retry(kwargs: { .. }) 
e: start_retry(kwargs: { .. })
f: start_retry(kwargs: { .. })
}
```
None

fix(subs): key collision on redis

---

.github/dependabot.yml
.github/workflows/tests.yml

- Makes sccache optional so PRs from dependabot and forks can still run the test suite.
- Increases sccache allotment to 50g.

fix(ci): disable sccache when secrets not avail

---

src/typegate/src/engine/typecheck/result.ts
src/typegate/src/runtimes/typegraph.ts
src/typegate/src/typegraph/mod.ts
src/typegate/src/typegraph/type_node.ts
tests/typecheck/__snapshots__/typecheck_test.ts.snap
tests/typecheck/typecheck.py
tests/typecheck/typecheck_test.ts

* Allow empty object on the output without any change
* Just like `Int`, `String`, and such, rightfully refer the constant `{}` as a scalar
* **Any** empty object will now be refered as  `EmptyObject` scalar
None

feat(gate): empty object as custom scalar

---

examples/typegraphs/metagen/rs/fdk.rs
src/meta-cli/src/cli/gen.rs
src/meta-cli/src/deploy/actors/task_io.rs
src/meta-cli/src/deploy/actors/task_manager.rs
src/typegraph/deno/src/io.ts
src/typegraph/python/typegraph/io.py

- Send the JSON-RPC message is chunks in the TypeScript typegraph client to prevent reaching the line size limit for stdout. Note: we could not reproduce the issue locally as it only occurs when using the published package for Node.js.
- Use JSON-RPC notification for logging and report from the typegraph clients.
- Other changes:
- Use relative paths for static task sources in the CLI;
- Fix TODO in `meta gen`: pass the working directory on the `working_dir` param of `SerializeActionGenerator::new`.
_N/A_
---

fix(typegraph): send rpc message in chunks in the TS typegraph client 

---

.ghjk/lock.json
Cargo.lock
Cargo.toml
src/meta-cli/Cargo.toml
src/meta-cli/src/cli/deploy.rs
src/meta-cli/src/cli/typegate.rs
src/meta-cli/src/deploy/actors/task_manager.rs
src/meta-cli/src/deploy/actors/task_manager/signal_handler.rs
src/meta-cli/src/deploy/actors/typegate.rs
tests/e2e/cli/dev_test.ts
tests/utils/process.ts

fix: meta dev does not exit properly upon `SIGTERM`

---

deno.lock
src/typegraph/core/src/params/apply.rs
tests/params/apply_test.ts
tests/params/prisma_apply.py

- Fix the optional field filter on apply: resolve types before matching.
_No migrations needed._
---

fix: fix optional field filter in apply

---

src/meta-cli/src/cli/gen.rs
src/meta-cli/src/cli/list.rs
src/meta-cli/src/cli/serialize.rs
src/meta-cli/src/deploy/actors/task/action.rs
src/meta-cli/src/deploy/actors/task/command.rs
src/meta-cli/src/deploy/actors/task/deploy.rs
src/meta-cli/src/deploy/actors/task/list.rs
src/meta-cli/src/deploy/actors/task/serialize.rs
src/typegraph/deno/src/envs/cli.ts
src/typegraph/python/typegraph/envs/cli.py

- Fixes [MET-738](https://linear.app/metatypedev/issue/MET-738/implement-prefix-in-meta-serialize).
---

fix(cli): implement `--prefix` argument

---

.ghjk/lock.json
ghjk.ts
src/metagen/src/client_ts/static/mod.ts
src/typegate/src/log.ts
src/typegate/standalone/src/logger.rs
src/typegraph/core/src/runtimes/mod.rs
src/typegraph/core/wit/typegraph.wit
src/typegraph/deno/src/providers/prisma.ts
src/typegraph/deno/src/typegraph.ts
src/typegraph/python/typegraph/providers/prisma.py

- Remove prisma count operation: it does not work, making it work like on the prisma client would complicate the prisma runtime (until we have output transformations...); Use aggregate instead.
- Increase the delay before exiting the process on the nodejs typegraph client to give the CLI time to process all the output.
- Remove `quaint` logs on the typegate (too verbose).
---

fix: Remove prisma count

---

Cargo.lock
Cargo.toml
examples/templates/deno/api/example.ts
examples/templates/deno/compose.yml
examples/templates/node/compose.yml
examples/templates/node/package.json
examples/templates/python/compose.yml
examples/templates/python/pyproject.toml
pyproject.toml
src/pyrt_wit_wire/pyproject.toml
src/typegate/src/runtimes/deno/deno.ts
src/typegate/src/runtimes/wit_wire/mod.ts
src/typegraph/core/Cargo.toml
src/typegraph/core/src/global_store.rs
src/typegraph/deno/deno.json
src/typegraph/python/pyproject.toml
src/typegraph/python/typegraph/__init__.py
src/xtask/Cargo.toml
tests/artifacts/artifacts_test.ts
tests/metagen/__snapshots__/metagen_test.ts.snap
tests/metagen/typegraphs/sample/rs/Cargo.toml
tests/metagen/typegraphs/sample/rs_upload/Cargo.toml
tests/runtimes/deno/deno.py
tests/runtimes/deno/deno_sync_test.ts
tests/runtimes/deno/deno_test.ts
tests/runtimes/deno/ts/deno.ts
tests/runtimes/substantial/workflows/workflow.ts
tests/runtimes/wasm_reflected/rust/Cargo.toml
tools/consts.ts

- Bumps to 0.5.0-rc.9
- Fixes bug with deno secret injection
---

fix: broken deno runtime secret injection
